//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMPPL
{
    using DevExpress.Mvvm.DataAnnotations;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [POCOViewModel(ImplementIDataErrorInfo = true)]
    public partial class CustmerMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustmerMaster()
        {
            this.Dispatches = new HashSet<Dispatch>();
        }
    
        public decimal CustId { get; set; }

        [Required(ErrorMessage = "Please enter the Customer name.")]
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string PhNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dispatch> Dispatches { get; set; }
    }
}
