//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMPPL
{
    using DevExpress.Mvvm.DataAnnotations;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    [POCOViewModel(ImplementIDataErrorInfo = true)]
    public partial class Dispatch
    {
        public static Dispatch CurrObject;
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dispatch()
        {
            this.LabelPrintings = new HashSet<LabelPrinting>();
            CurrObject = this;
        }
        
        public decimal DptId { get; set; }

        [Required(ErrorMessage = "Please Select Customer.")]
        public Nullable<decimal> CustomerId { get; set; }

        [Required(ErrorMessage = "Please Select Date.")]
        public Nullable<System.DateTime> DispatchDate { get; set; }
        public string TruckNo { get; set; }
        public string DriverName { get; set; }
    
        public virtual CustmerMaster CustmerMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabelPrinting> LabelPrintings { get; set; }

        
    }
}
