//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMPPL
{
    using DevExpress.Mvvm.DataAnnotations;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Data.SqlClient;
    [POCOViewModel(ImplementIDataErrorInfo = true)]
    public partial class LabelPrinting
    {
        public static LabelPrinting LastObject = null;
        public decimal LblId { get; set; }

        [Required(ErrorMessage = "Please Select Size")]
        public Nullable<decimal> SizeId { get; set; }

        [Required(ErrorMessage = "Please Select Micron")]
        public Nullable<decimal> MicronId { get; set; }

        [Required(ErrorMessage = "Please Select Grade")]
        public Nullable<decimal> GradeId { get; set; }

        [Required(ErrorMessage = "Please Select Color")]
        public Nullable<decimal> ColorId { get; set; }

        [Required(ErrorMessage = "Please Enter Gross Weight")]
        public string GrossWeight { get; set; }
        public string NetWeight { get; set; }
        public string SRNO { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public Nullable<decimal> DptId { get; set; }
    
        public virtual ColorMaster ColorMaster { get; set; }
        public virtual Dispatch Dispatch { get; set; }
        public virtual GradeMaster GradeMaster { get; set; }
        public virtual MicronMaster MicronMaster { get; set; }
        public virtual SizeMaster SizeMaster { get; set; }
        public LabelPrinting()
        {
            SqlConnection con = new SqlConnection(Properties.Settings.Default.strCon);
            if (con.State != System.Data.ConnectionState.Open)
            {
                con.Open();
            }
            string curBatch = DateTime.Today.ToString("ddMMyy");
            string sqlString = "Select isnull(Max(cast(SUBSTRING ( SRNO ,7,Len(SRNO) ) as int))+1,1) as SRNO from LabelPrinting" +
                    " where SUBSTRING ( SRNO ,1,6 )='" + curBatch + "'";
            SqlCommand cmd = new SqlCommand(sqlString, con);
            int srn = (int)cmd.ExecuteScalar();
            SRNO = curBatch + srn.ToString("0000");
            if (con.State == System.Data.ConnectionState.Open)
            {
                cmd.Dispose();
                con.Close();
                con.Dispose();
            }
            if(LastObject!=null)
            {
                this.SizeId = LastObject.SizeId;
                this.ColorId = LastObject.ColorId;
                this.GradeId = LastObject.GradeId;
                this.MicronId = LastObject.MicronId;
            }
            LastObject = this;
            // SRNO= DateTime.Today.ToString("ddMMyy");
        }
    }
}
