//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMPPL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MMPPLDBEntities : DbContext
    {
        public MMPPLDBEntities()
            : base("name=MMPPLDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ColorMaster> ColorMasters { get; set; }
        public virtual DbSet<CustmerMaster> CustmerMasters { get; set; }
        public virtual DbSet<Dispatch> Dispatches { get; set; }
        public virtual DbSet<GradeMaster> GradeMasters { get; set; }
        public virtual DbSet<LabelPrinting> LabelPrintings { get; set; }
        public virtual DbSet<MicronMaster> MicronMasters { get; set; }
        public virtual DbSet<SizeMaster> SizeMasters { get; set; }
        public virtual DbSet<DuplicatePrinting> DuplicatePrintings { get; set; }
        public virtual DbSet<StockReport> StockReports { get; set; }
    }
}
