//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMPPL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockReport
    {
        public int EDMXID { get; set; }
        public Nullable<decimal> SizeId { get; set; }
        public string SizeName { get; set; }
        public Nullable<decimal> MicronId { get; set; }
        public string MicronName { get; set; }
        public Nullable<decimal> GradeId { get; set; }
        public string GradeName { get; set; }
        public Nullable<decimal> ColorId { get; set; }
        public string ColorName { get; set; }
        public Nullable<double> TotalGrossWeight { get; set; }
        public Nullable<double> TotalNetWeight { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
